site_name: pymmcore-widgets
site_url: https://github.com/pymmcore-plus/pymmcore-widgets

# Repository
repo_name: pymmcore-plus/pymmcore-widgets
repo_url: https://github.com/pymmcore-plus/pymmcore-widgets

theme:
  icon:
    logo: material/book-education-outline
  name: material
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - scheme: slate
      primary: blue grey
      accent: blue grey
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode
markdown_extensions:
  - admonition
